const names = [
    "	Godzilla	"	,
"	Luke	"	,
"	Chewie	"	,
"	Ripley	"	,
"	Air Bud	"	,
"	Asta	"	,
"	Peckinpah	"	,
"	Beethoven	"	,
"	Perdita	"	,
"	Toto	"	,
"	Barney	"	,
"	Jawa	"	,
"	Jupiter	"	,
"	Beast	"	,
"	Bronson	"	,
"	Marry Puppins	"	,
"	Cthulhu	"	,
"	Alice	"	,
"	Hamlet	"	,
"	Gatsby	"	,
"	Zelda	"	,
"	Melville	"	,
"	Shakespeare	"	,
"	Lovecraft	"	,
"	Caulfield	"	,
"	Sawyer	"	,
"	Sport	"	,
"	Cujo	"	,
"	Marley	"	,
"	Ramona	"	,
"	Shelley	"	,
"	Bark Twain	"	,
"	Poochie	"	,
"	Snoopy	"	,
"	Tinkie Winkie	"	,
"	Stewie	"	,
"	Walter White	"	,
"	Hannity	"	,
"	Scooby-Doo	"	,
"	Pikachu	"	,
"	Pugsley	"	,
"	Alf	"	,
"	Lucy	"	,
"	Veronica Mars	"	,
"	Conan	"	,
"	Magnum	"	,
"	Judge Judy	"	,
"	Sarah Jessica Barker	"	,
"	Winnie The Poodle	"	,
"	Charles Barkley	"	,
"	Sir Barks-a-lot	"	,
"	Virginia Woof	"	,
"	James Earl Bones	"	,
"	Jerry Chewis	"	,
"	Chattanooga Chew-Chew	"	,
"	MacGruff	"	,
"	Bob Barker	"	,
"	Mutt Romney	"	,
"	Bea Arfur	"	,
"	Andy Warhowl	"	,
"	Babe Woof	"	,
"	Lick Jagger	"	,
"	The Wizard of Paws	"	,
"	LL Drool J	"	,
"	Buck	"	,
"	Big Red	"	,
"	Bruiser	"	,
"	Fred	"	,
"	Wolf	"	,
"	Caesar	"	,
"	Prince	"	,
"	Major	"	,
"	Chief	"	,
"	Rex	"	,
"	Kitty	"	,
"	Hobbit	"	,
"	Ditka	"	,
"	Moose	"	,
"	Tiberius	"	,
"	Bloopy	"	,
"	Tootsie	"	,
"	Nibblets	"	,
"	Tiny	"	,
"	Wonton	"	,
"	Peanut	"	,
"	Zippy	"	,
"	Tuffy	"	,
"	Bowser	"	,
"	Kong	"	,
"	Buster	"	,
"	Chubby	"	,
"	Pistol	"	,
"	Marshmallow	"	,
"	Penny	"	,
"	Clyde	"	,
"	Dave	"	,
"	Oreo	"	,
"	Porkchop	"	,
"	Shinobi	"	,
"	Bucky	"	,
"	Tiger	"	,
"	Bubba	"	,
"	Brando	"	,
"	Mugsy	"	,
"	Peter Pan	"	,
"	Gucci	"	,
"	Eggbert	"	,
"	Cheeto	"	,
"	Pickle	"	,
"	Mitzi	"	,
"	Daisy	"	,
"	Trix	"	,
"	Bo Peep	"	,
"	Goldilocks	"	,
"	Caramel	"	,
"	Puddin	"	,
"	Myrtle	"	,
"	Izzy	"	,
"	Cupcake	"	,
"	Tinkerbell	"	,
"	Prada	"	,
"	Buttercup	"	,
"	Cleopatra	"	,
"	Fifi	"	,
"	Rolo	"	,
"	Taco	"	,
"	Meatball	"	,
"	Nugget	"	,
"	Bonbon	"	,
"	Tamale	"	,
"	Ziti	"	,
"	Candy	"	,
"	Snickerdoodle	"	,
"	Dumpling	"	,
"	Taffy	"	,
"	Pumpkin	"	,
"	Stringbean	"	,
"	Butterscotch	"	,
"	Raspberry	"	,
"	Pup Tart	"	
]

const getRandomName = () =>{
   return (names[Math.floor(Math.random() * names.length)].trim());
}
const getRandomAge = () =>{
    return (Math.floor(Math.random() * 10) + 1)
}


module.exports = {
    getRandomName,
    getRandomAge,

  };
  